<?php

use App\Enums\FixJobStatus;
use App\Enums\FixJobType;
use App\Models\FixJob;
use App\Services\Autofix\AppliedDiff;
use App\Services\Autofix\DiffValidator;
use App\Services\Autofix\GitHubAppException;
use App\Services\Autofix\PullRequestPublisher;
use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;

beforeEach(function () {
    $key = openssl_pkey_new(['private_key_type' => OPENSSL_KEYTYPE_RSA, 'private_key_bits' => 2048]);
    openssl_pkey_export($key, $privatePem);

    config([
        'autofix.enabled' => true,
        'autofix.github.app_id' => '123456',
        'autofix.github.private_key' => base64_encode($privatePem),
    ]);
});

/**
 * A validated job, ready to publish, with its diff already applied.
 *
 * @param  array<string, mixed>  $attributes
 * @return array{0: FixJob, 1: AppliedDiff}
 */
function publishableJob(array $attributes = []): array
{
    $job = ayosJob();
    $job->forceFill([
        'status' => FixJobStatus::Validating,
        'fingerprint' => 'abcdef0123456789abcdef',
        'diff' => billingDiff(),
        'report' => [
            'summary' => 'Guarded the missing "total" key with a null coalesce.',
            'tests' => ['cmd' => 'php artisan test --compact', 'passed' => true],
            'links' => ['https://bilis.test/acme/logs?search=PaymentFailed'],
        ],
        ...$attributes,
    ])->save();

    $applied = app(DiffValidator::class)->validate($job)->applied();

    return [$job, $applied];
}

test('it pushes blobs, a tree, a commit and a branch, then opens the pull request', function () {
    fakeGitHubRepository(billingFiles());

    [$job, $applied] = publishableJob();

    app(PullRequestPublisher::class)->publish($job, $applied);

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/blobs' || $request->method() !== 'POST') {
            return false;
        }

        expect($request->data()['encoding'])->toBe('base64')
            ->and(base64_decode($request->data()['content'], true))
            ->toBe("<?php\n\$total = \$order['total'] ?? 0;\nreturn \$total;\n");

        return true;
    });

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/trees' || $request->method() !== 'POST') {
            return false;
        }

        expect($request->data()['base_tree'])->toBe('tree-of-head1234567890')
            ->and($request->data()['tree'])->toBe([[
                'path' => 'app/Billing.php',
                'mode' => '100644',
                'type' => 'blob',
                'sha' => 'created-blob',
            ]]);

        return true;
    });

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/commits') {
            return false;
        }

        expect($request->data()['tree'])->toBe('created-tree')
            ->and($request->data()['parents'])->toBe(['head1234567890'])
            ->and($request->data()['message'])->toContain('Machine-generated by Bilis autofix.');

        return true;
    });

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/refs') {
            return false;
        }

        expect($request->data())->toBe([
            'ref' => 'refs/heads/autofix/abcdef012345',
            'sha' => 'created-commit',
        ]);

        return true;
    });

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/pulls' || $request->method() !== 'POST') {
            return false;
        }

        expect($request->data()['head'])->toBe('autofix/abcdef012345')
            ->and($request->data()['base'])->toBe('main')
            ->and($request->data()['title'])->toBe('Fix PaymentFailed: Charge declined for order 4821')
            ->and($request->data()['body'])->toContain('Machine-generated — review carefully')
            ->and($request->data()['body'])->toContain('Guarded the missing "total" key with a null coalesce.')
            ->and($request->data()['body'])->toContain('| Occurrences | 9 |')
            ->and($request->data()['body'])->toContain('`app/Billing.php`')
            ->and($request->data()['body'])->toContain('https://bilis.test/acme/logs?search=PaymentFailed');

        return true;
    });

    $job->refresh();

    expect($job->status)->toBe(FixJobStatus::PrOpened)
        ->and($job->pr_number)->toBe(42)
        ->and($job->pr_url)->toBe('https://github.com/acme/app/pull/42');
});

test('the write token asks for contents and pull requests and is never cached', function () {
    fakeGitHubRepository(billingFiles());

    [$job, $applied] = publishableJob();

    Cache::flush();

    app(PullRequestPublisher::class)->publish($job, $applied);
    app(PullRequestPublisher::class)->publish($job, $applied);

    $writeRequests = 0;

    Http::assertSent(function (Request $request) use (&$writeRequests) {
        if (! str_contains($request->url(), 'access_tokens')) {
            return false;
        }

        if ($request->data()['permissions'] === ['contents' => 'write', 'pull_requests' => 'write']) {
            $writeRequests++;

            expect($request->data()['repositories'])->toBe(['app'])
                ->and($request->data()['permissions'])->not->toHaveKey('workflows');
        }

        return true;
    });

    /*
     * Two publishes, two token exchanges: a write token is never read back
     * out of the cache, however short its life would have been.
     */
    expect($writeRequests)->toBe(2);
});

test('a stale branch from an earlier attempt is force updated', function () {
    fakeGitHubRepository(billingFiles(), [
        'api.github.com/repos/acme/app/git/refs' => Http::sequence()
            ->push(['message' => 'Reference already exists'], 422)
            ->push(['ref' => 'refs/heads/autofix/abcdef012345'], 200),
        'api.github.com/repos/acme/app/git/refs/heads/*' => Http::response(['ref' => 'refs/heads/autofix/abcdef012345']),
    ]);

    [$job, $applied] = publishableJob();

    app(PullRequestPublisher::class)->publish($job, $applied);

    Http::assertSent(function (Request $request) {
        if ($request->method() !== 'PATCH') {
            return false;
        }

        expect($request->url())->toBe('https://api.github.com/repos/acme/app/git/refs/heads/autofix/abcdef012345')
            ->and($request->data())->toBe(['sha' => 'created-commit', 'force' => true]);

        return true;
    });

    expect($job->fresh()->status)->toBe(FixJobStatus::PrOpened);
});

test('a pull request that already exists for the branch is adopted', function () {
    fakeGitHubRepository(billingFiles(), [
        'api.github.com/repos/acme/app/pulls?*' => Http::response([
            ['number' => 7, 'html_url' => 'https://github.com/acme/app/pull/7'],
        ]),
        'api.github.com/repos/acme/app/pulls' => Http::response(['message' => 'A pull request already exists'], 422),
    ]);

    [$job, $applied] = publishableJob();

    app(PullRequestPublisher::class)->publish($job, $applied);

    expect($job->fresh()->pr_number)->toBe(7)
        ->and($job->fresh()->pr_url)->toBe('https://github.com/acme/app/pull/7');
});

test('a deletion becomes a tree entry with a null sha', function () {
    fakeGitHubRepository(['legacy.php' => "<?php\n// gone\n"]);

    $job = ayosJob();
    $job->forceFill([
        'status' => FixJobStatus::Validating,
        'diff' => "diff --git a/legacy.php b/legacy.php\ndeleted file mode 100644\n--- a/legacy.php\n+++ /dev/null\n@@ -1,2 +0,0 @@\n-<?php\n-// gone\n",
    ])->save();

    $applied = app(DiffValidator::class)->validate($job)->applied();

    app(PullRequestPublisher::class)->publish($job, $applied);

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/trees' || $request->method() !== 'POST') {
            return false;
        }

        expect($request->data()['tree'])->toBe([[
            'path' => 'legacy.php',
            'mode' => '100644',
            'type' => 'blob',
            'sha' => null,
        ]]);

        return true;
    });

    Http::assertNotSent(fn (Request $request) => $request->url() === 'https://api.github.com/repos/acme/app/git/blobs' && $request->method() === 'POST');
});

test('a GitHub failure while publishing raises a typed exception', function () {
    fakeGitHubRepository(billingFiles(), [
        'api.github.com/repos/acme/app/git/commits' => Http::response(['message' => 'Server error'], 500),
    ]);

    [$job, $applied] = publishableJob();

    try {
        app(PullRequestPublisher::class)->publish($job, $applied);

        $this->fail('The publisher swallowed a GitHub failure.');
    } catch (GitHubAppException $exception) {
        expect($exception->isTransient())->toBeTrue()
            ->and($exception->statusCode())->toBe(500);
    }

    expect($job->fresh()->status)->toBe(FixJobStatus::Validating);
});

test('a custom job branches off its uuid and describes the request instead of an error', function () {
    fakeGitHubRepository(billingFiles());

    [$job, $applied] = publishableJob([
        'type' => FixJobType::Custom,
        'fingerprint' => null,
        'error_context' => null,
        'instructions' => 'Add a /healthz endpoint that returns 204 and touches no database.',
        'report' => [
            'summary' => 'Added a HealthController with a single 204 route.',
            'tests' => ['cmd' => 'php artisan test --compact', 'passed' => true],
        ],
    ]);

    app(PullRequestPublisher::class)->publish($job, $applied);

    $branch = 'autofix/custom-'.mb_substr($job->uuid, 0, 12);

    expect(app(PullRequestPublisher::class)->branch($job))->toBe($branch);

    Http::assertSent(function (Request $request) use ($branch) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/refs') {
            return false;
        }

        expect($request->data()['ref'])->toBe('refs/heads/'.$branch);

        return true;
    });

    Http::assertSent(function (Request $request) use ($job) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/pulls' || $request->method() !== 'POST') {
            return false;
        }

        $body = $request->data()['body'];

        expect($request->data()['head'])->toBe('autofix/custom-'.mb_substr($job->uuid, 0, 12))
            ->and($request->data()['title'])->toBe('Add a /healthz endpoint that returns 204 and touches no database.')
            /* The warning block names the source: a request, not an error report. */
            ->and($body)->toContain("> **Machine-generated — review carefully.** A coding agent wrote this change from a team member's request. Nobody has read it yet. Review it as you would a patch from a stranger, and do not merge it because CI is green.")
            ->and($body)->toContain('## The request')
            ->and($body)->toContain('Add a /healthz endpoint that returns 204 and touches no database.')
            ->and($body)->toContain('Added a HealthController with a single 204 route.')
            ->and($body)->toContain('[This job in Bilis]')
            ->and($body)->not->toContain('## The error')
            ->and($body)->not->toContain('| Fingerprint |')
            ->and($body)->not->toContain('| Occurrences |');

        return true;
    });

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/git/commits' || $request->method() !== 'POST') {
            return false;
        }

        expect($request->data()['message'])
            ->toContain('Requested by a team member.')
            ->not->toContain('Fingerprint:');

        return true;
    });
});

test('a custom job with an unusable request still gets a title', function () {
    fakeGitHubRepository(billingFiles());

    [$job, $applied] = publishableJob([
        'type' => FixJobType::Custom,
        'fingerprint' => null,
        'error_context' => null,
        'instructions' => '   ',
    ]);

    app(PullRequestPublisher::class)->publish($job, $applied);

    Http::assertSent(function (Request $request) {
        if ($request->url() !== 'https://api.github.com/repos/acme/app/pulls' || $request->method() !== 'POST') {
            return false;
        }

        expect($request->data()['title'])->toBe('Requested repository change')
            ->and($request->data()['body'])->toContain('(no request was recorded)');

        return true;
    });
});
